spring:
  sleuth:
    sampler:
      probability: 1.0
  cloud:
    gateway:
      routes:
      # order-service
      - uri: lb://b2c-order-service
        predicates:
        - Path=/api-order/**
        filters:
        - name: Hystrix
          args:
            name: order-fallback
            fallbackUri: forward:/fallback
      # store-service
      - uri: lb://b2c-store-service
        predicates:
        - Path=/api-store/**
        filters:
        - name: Hystrix
          args:
            name: store-fallback
            fallbackUri: forward:/fallback
      # customer-service
      - uri: lb://b2c-customer-service
        predicates:
        - Path=/api-customer/**
        filters:
        - name: Hystrix
          args:
            name: customer-fallback
            fallbackUri: forward:/fallback
      # message-service
      - uri: lb://b2c-message-service
        predicates:
        - Path=/api-message/**
        filters:
        - name: Hystrix
          args:
            name: message-fallback
            fallbackUri: forward:/fallback
      # pay-service
      - uri: lb://b2c-pay-service
        predicates:
        - Path=/api-pay/**
        filters:
        - name: Hystrix
          args:
            name: pay-fallback
            fallbackUri: forward:/fallback
      # promotion-service
      - uri: lb://b2c-promotion-service
        predicates:
        - Path=/api-promotion/**
        filters:
        - name: Hystrix
          args:
            name: promotion-fallback
            fallbackUri: forward:/fallback