spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: NON_NULL
    time-zone: GMT+8
  mvc:
    locale: zh
  sleuth:
    sampler:
      probability: 1
#  zipkin:
#    sender:
#      type: rabbit
#  zipkin:
#    base-url: http://localhost:8080
  kafka:
    producer:
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
        
  zipkin:
    kafka: true
    sender:
      type: kafka
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092,localhost:9093,localhost:9094
          zkNodes: localhost:2181,localhost:2182,localhost:2183
        
          
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 30
      idle-timeout: 180000
      auto-commit: true
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: select 1
      
zipkin:
  storage:
    type: elasticsearch
    elasticsearch:
      host: localhost:9200
      cluster: elasticsearch
      index: zipkin
      index-shards: 1
      index-replicas: 1
      
management:
  endpoints:
    web:
      exposure:
        include: "*"
      path-mapping:
        shutdown: /shut/down/server
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always

eureka:
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 5
  client:
    registry-fetch-interval-seconds: 5

feign.hystrix.enabled: false

hystrix.command.default.execution.isolation.strategy: THREAD
hystrix.threadpool.default.coreSize: 20
hystrix.threadpool.default.maximumSize: 200
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 10000
hystrix.command.default.execution.isolation.semaphore.maxConcurrentRequests: 200

ribbon:
  ServerListRefreshInterval: 2000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  OkToRetryOnAllOperations: false
  ConnectTimeout: 2000
  ReadTimeout: 10000