spring:
  sleuth:
    sampler:
      probability: 1.0
  cloud:
    gateway:
      routes:
      # order-service
      - uri: lb://b2c-order-service
        predicates:
        - Path=/api-order/**
        filters:
        - name: Hystrix
          args:
            name: order-fallback
            fallbackUri: forward:/fallback
