spring:
  messages:
    encoding: utf-8
    basename: i18n/codes
    fallback-to-system-locale: false

cdn:
   #cdn 上传文件服务器路径，文件不覆盖
   picture: http://upload.winhxd.com:8100/crm/uploadResource2CDNAction.do?method=addRecordNewJson